name: test_repo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1
scripts:
  analyze: "flutter analyze"
  gen: "flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs"
  watch: "flutter pub run build_runner watch --delete-conflicting-outputs"
  fix:
    ios: "cd ios && rm -rf Podfile.lock && pod deintegrate && pod install && pod repo update && pod install && cd .."
  build:
    android:
      # rps build android apk
      apk: ^2.4.7
      # rps build android appbundle
      appbundle: "flutter build appbundle --release --target-platform android-arm,android-arm64 --obfuscate --split-debug-info=build/app/outputs/symbols/android"
      # and so on...


environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  image_picker: ^1.0.5
  intl: ^0.18.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  webview_flutter: ^4.4.2


dev_dependencies:
  #  flutter_test:
  flutter_localizations:
    sdk: flutter


  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: any
  very_good_analysis: ^5.1.0


flutter:


  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - fonts/
    - assets/images/


  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/Gilroy-Bold.ttf
        - asset: fonts/Gilroy-Light.ttf
        - asset: fonts/Gilroy-Medium.ttf
        - asset: fonts/Gilroy-Regular.ttf
        - asset: fonts/Gilroy-Thin.ttf